version: "3"
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my-network
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - my-network

  db:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my-network

  app:
    image: my-app:1
    container_name: my-app
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - db
      - kafka
    ports:
      - "8080:8081"


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
    ports:
      - "9200:9200"
    networks:
      - my-network

  search:
    image: search-app:1
    container_name: search-app
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - elasticsearch
    environment:
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    ports:
      - "8081:8082"

networks:
  my-network:
